sudo: false
language: python
python:
  - "3.6.2"
services:
  - docker
env:
  global:
    - secure: 
script:
  - docker build -t kishanb/fibs:1.0.0 .
after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push kishanb/fibs:1.0.0